### ISSUE TITLE
Plotting error thrown in shmlast run? 

### ISSUE THREAD

**Issue by halexand** [camillescott/shmlast#4]
## Problem Description
An error mid-way through running shmlast on HPC. 

## My Environment
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux

### Python Environment
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 

### LAST Version
658? Downloaded as per your instructions in version 1.1
### Shmlast Output

```
--- Begin Task Execution ---
-- rename:../assemblies/MMETSP0004.trinity_out_2.2.0.Trinity.fasta: 
    * Python: rename_input
-- rename:../transdecoder_pep/MMETSP0005.Trinity.fixed.fa.transdecoder.pep: 
    * Python: rename_input
-- translate:.MMETSP0004.trinity_out_2.2.0.Trinity.fasta: 
    * Python: function translate_fastx
-- lastdb:.MMETSP0004.trinity_out_2.2.0.Trinity.fasta.pep: 
    * Cmd: `/mnt/home/alexa503/bin/lastdb -p -w3 .MMETSP0004.trinity_out_2.2.0.Trinity.fasta.pep .MMETSP0004.trinity_out_2.2.0.Trinity.fasta.pep`
-- lastdb:.MMETSP0005.Trinity.fixed.fa.transdecoder.pep: 
    * Cmd: `/mnt/home/alexa503/bin/lastdb -p -w3 .MMETSP0005.Trinity.fixed.fa.transdecoder.pep .MMETSP0005.Trinity.fixed.fa.transdecoder.pep`
-- lastal:.MMETSP0005.Trinity.fixed.fa.transdecoder.pep.x.MMETSP0004.trinity_out_2.2.0.Trinity.fasta.pep.maf: 
    * Cmd: `cat .MMETSP0005.Trinity.fixed.fa.transdecoder.pep | /mnt/home/alexa503/bin/parallel --round-robin --pipe -L 2 -N 10000 --gnu -j 8 -a .MMETSP0005.Trinity.fixed.fa.transdecoder.pep /mnt/home/alexa503/bin/lastal -D100000.0 .MMETSP0004.trinity_out_2.2.0.Trinity.fasta.pep > .MMETSP0005.Trinity.fixed.fa.transdecoder.pep.x.MMETSP0004.trinity_out_2.2.0.Trinity.fasta.pep.maf`
-- lastal:.MMETSP0004.trinity_out_2.2.0.Trinity.fasta.pep.x.MMETSP0005.Trinity.fixed.fa.transdecoder.pep.maf: 
    * Cmd: `cat .MMETSP0004.trinity_out_2.2.0.Trinity.fasta.pep | /mnt/home/alexa503/bin/parallel --round-robin --pipe -L 2 -N 10000 --gnu -j 8 -a .MMETSP0004.trinity_out_2.2.0.Trinity.fasta.pep /mnt/home/alexa503/bin/lastal -D100000.0 .MMETSP0005.Trinity.fixed.fa.transdecoder.pep > .MMETSP0004.trinity_out_2.2.0.Trinity.fasta.pep.x.MMETSP0005.Trinity.fixed.fa.transdecoder.pep.maf`
.  fit_and_filter_crbl_hits: 
    * Python: do_crbl_fit_and_filter
/mnt/home/alexa503/anaconda3/lib/python3.5/site-packages/shmlast/crbl.py:90: RuntimeWarning: invalid value encountered in log10
  df[scaled_col_name] = -np.log10(df[scaled_col_name])
########################################
TaskError - taskid:fit_and_filter_crbl_hits
PythonAction Error
Traceback (most recent call last):
  File "/mnt/home/alexa503/anaconda3/lib/python3.5/site-packages/doit/tools.py", line 218, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/mnt/home/alexa503/anaconda3/lib/python3.5/site-packages/shmlast/app.py", line 244, in do_crbl_fit_and_filter
    plot_crbh_fit(model_df, hits_df, self.model_plot_fn)
  File "/mnt/home/alexa503/anaconda3/lib/python3.5/site-packages/shmlast/crbl.py", line 181, in plot_crbh_fit
    line_kws=line_kws, color=scatter_kws['c'], ax=ax)
  File "/mnt/home/alexa503/anaconda3/lib/python3.5/site-packages/seaborn/linearmodels.py", line 779, in regplot
    plotter.plot(ax, scatter_kws, line_kws)
  File "/mnt/home/alexa503/anaconda3/lib/python3.5/site-packages/seaborn/linearmodels.py", line 330, in plot
    self.scatterplot(ax, scatter_kws)
  File "/mnt/home/alexa503/anaconda3/lib/python3.5/site-packages/seaborn/linearmodels.py", line 359, in scatterplot
    ax.scatter(x, y, **kws)
  File "/mnt/home/alexa503/anaconda3/lib/python3.5/site-packages/matplotlib/__init__.py", line 1892, in inner
    return func(ax, *args, **kwargs)
  File "/mnt/home/alexa503/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 3931, in scatter
    raise ValueError("Supply a 'c' kwarg or a 'color' kwarg"
ValueError: Supply a 'c' kwarg or a 'color' kwarg but not both; they differ but their functionalities overlap.
```

**Comment by camillescott** [comment]
Fixed in 1.2
